# Generated by Django 4.2.1 on 2025-11-24 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0003_opportunitytask'),
        ('common', '0009_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='opportunity_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_attachments', to='opportunity.opportunitytask'),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachment_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
