# Generated by Django 4.2.1 on 2025-11-24 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0009_user_is_staff'),
        ('opportunity', '0002_alter_opportunity_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stage', models.CharField(choices=[('discovery', 'Discovery'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='opportunity.opportunity')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_tasks', to='common.org')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Opportunity Task',
                'verbose_name_plural': 'Opportunity Tasks',
                'db_table': 'opportunity_task',
                'ordering': ('stage', 'order', '-created_at'),
            },
        ),
    ]
