# Generated by Django 4.2.1 on 2025-11-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0003_opportunitytask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('DISCOVERY', 'Discovery'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('CLOSED WON', 'CLOSED WON'), ('CLOSED LOST', 'CLOSED LOST')], max_length=64, verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='opportunitytask',
            name='stage',
            field=models.CharField(choices=[('DISCOVERY', 'Discovery'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation')], max_length=20),
        ),
    ]
