# Generated by Django 4.2.1 on 2025-11-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0004_alter_opportunity_stage_alter_opportunitytask_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='discovery_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='proposal_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
