# Generated by Django 4.2.1 on 2025-11-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0005_opportunity_discovery_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('DISCOVERY', 'Discovery'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('CLOSED WON', 'CLOSED WON'), ('CLOSED LOST', 'CLOSED LOST')], default='DISCOVERY', max_length=64, verbose_name='Stage'),
        ),
    ]
