# Generated by Django 4.2.1 on 2025-11-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0006_alter_opportunity_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitytask',
            name='stage',
            field=models.CharField(choices=[('DISCOVERY', 'Discovery'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('CLOSED WON', 'Closed Won'), ('CLOSED LOST', 'Closed Lost')], max_length=20),
        ),
    ]
